---
title: "rapa_lab"
format: html
editor: visual
---

```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

```{r}

ei_points <- st_read(here('week1',"data", "easter_island", "ei_points.gpkg")) |> filter(type == "volcano")
ei_elev <- read_stars(here('week1',"data", "easter_island", "ei_elev.tif"))
ei_borders <- st_read(here('week1',"data", "easter_island", "ei_border.gpkg"))
ei_roads <- st_read(here('week1',"data", "easter_island", "ei_roads.gpkg"))
```

```{r}
#add easter island vector
  tm_shape(ei_borders) +
    tm_borders() +
#set general map layout options
    tm_layout(main.title = "Easter Island")
```

```{r}

ei_map <- tm_shape(ei_elev) +
  tm_graticules() + 
  tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"), col.legend = tm_legend("Elevation (m asl")) +
  tm_shape(ei_borders) +
  tm_borders() +
  tm_shape(ei_roads) +
  tm_lines() +
  tm_shape(ei_points) +
    tm_symbols(shape = 24,
             size = "elevation",
             size.legend = tm_legend("Volcano (m asl)")) +
  tm_compass(position = c("right", "top")) +
  tm_scalebar() +
  tm_title("Easter Island")

  

ei_map
```

```{r}
tmap_mode("view")
ei_map
```
